### ISSUE TITLE
Unhealthy container 

### ISSUE THREAD

**Issue by numbermonkey** [modem7/docker-starwars#10]
I'm not smart enough to resolve this. The container shows unhealthy and a dig into it shows
curl: (7) Failed to connect to 127.0.0.1 port 80 after 0 ms: Connection refused
I made the 8080 change (I point host 1977 -> Container 8080) but hasnt fixed :(
I miss my blinken.

**Comment by modem7** [comment]
Hey bud, do you have your compose file contents?

The healthcheck is already pointing to 8080 in this case, so issue may be elsewhere.

**Comment by numbermonkey** [comment]
Hey :)
I dont have a compose file. I started it with this
docker run --restart=always --name=starwars --detach -p 1977:8080 modem7/docker-starwars:latest
and now I manage it with Portainer.

**Comment by modem7** [comment]
Hmmm, that should definitely work.

I'll have a play with it and investigate what's occurring.

I'll keep you updated.

**Comment by modem7** [comment]
> Hey :) I dont have a compose file. I started it with this docker run --restart=always --name=starwars --detach -p 1977:8080 modem7/docker-starwars:latest and now I manage it with Portainer.

Hey bud, 

I've just run:

`docker run --restart=always --name=starwars -d -p 1977:8080 modem7/docker-starwars:latest`

And the healthcheck comes back healthy. 

It might be worthwhile removing the container + image and redownloading it, it might still be using the old image.

**Comment by numbermonkey** [comment]
SOLVED. A complete purge of image and container and a rerun of the docker setup resolved this.
Weird. Thanks modem7 :D

**Comment by modem7** [comment]
> SOLVED. A complete purge of image and container and a rerun of the docker setup resolved this.
> Weird. Thanks modem7 :D

Any time dude!

Do you run watchtower as well? It's an easier way to keep things up to date if you're not!

Glad it's all resolved with minimal tinkering!
